### ISSUE TITLE
online version of Cronometer

### ISSUE THREAD

**Issue by MalcolmMielle** [wbrenna/inventory#1]
Hello,

Is it possible to use the online version of cronometer ?

Best

**Comment by wbrenna** [comment]
Unfortunately, I don't think so! The online version isn't open source so there isn't really much I can do to synchronize to its food database. If they opened up an API then the answer would be 'probably', but I don't foresee them doing that. I think someone asked in the past: http://blog.cronometer.com/?topic=api-available.

**Comment by MalcolmMielle** [comment]
Ok, I don't really want to work on Cronometer. I'm thinking of implementing an other possibility of storing what item one have locally on the computer.
What do you think ? Would that be useful ? Should I use a database (postgre ?) or just store it in a file ?

If I understand the code correctly, the `inventoryarr` var is meant to store upc and description but do not store how many item we have. Why not add this possibility so you don't need to store them through Cronometer ?

**Comment by wbrenna** [comment]
Ideally for scalability a database would be smarter. Right now it uses a file, inventory.inv, which is the pickled inventoryarr. Because typically the inventory is small, performance with a file is fine.

The array does have the number of items, but indexed like `inventoryarr[upc][x]`. You just have to count the number of elements `x` and that gives the number of items with that UPC. The key there contains purchase dates for those items so you can have a list of the same thing with different expiry dates.

The cronometer integration is really only so that inventory.py knows details of the barcodes entered. Otherwise you have to enter those details yourself, or try to grab them from a website. When an item is scanned, inventory.py queries a cronometer database if it exists to grab the description of that UPC. No information gets fed back to cronometer, so it doesn't know anything about inventory.py.

**Comment by MalcolmMielle** [comment]
Hooooo, I though it was the other way around ! Some details are available through upcdatabase, ain't they ?

The file approach seemed good since it's mostly used in house so no big database. I'll see if it fits my needs like this.

**Comment by wbrenna** [comment]
Yes I think upcdatabase does have details but I haven't had great luck with it and it might need some API code with a limited number of accesses. I found that the best thing to do was just to slowly build up your own database.

Good luck!
